### ISSUE TITLE
The DualReader can handle only one of them

### ISSUE THREAD

**Issue by koriym** [koriym/Koriym.Attributes#10]
> @koriym Hi, I came to a bug when only annotations or attributes are used. The DualReader can handle only one of them, depending on PHP version.

> This caused missing annotations on PHP 8. I think more reliable solution would be class like this one - that reads both annotations and attributes on PHP 8, if available. That's what I expected from DualReader class and that's where it failed my expectations. But maybe there is a better way to do it.

From https://github.com/apitte/core/pull/165#pullrequestreview-702851750

**Comment by TomasVotruba** [comment]
I can fix it here... shall I send PR?

**Comment by koriym** [comment]
@TomasVotruba Yes! Thanks. But before that let me explain why I was doing it this way.

**Comment by TomasVotruba** [comment]
No problem. For us it's only important not to break previous behavior, which now happened.

**Comment by koriym** [comment]
When supporting PHP8, I assumed that both annotations and attributes would be added as follows.
 
 ```php
 /**
  * @Foo
  */
#[Foo]
class Fake
{
}
```

The reason why only one of them is read is for performance. There is no performance loss (PHP source parsing cost) for the dual reader when you start with a mixed library of php7 and php8 attributes and end up with "only" php8 attributes.

This was the way I envisioned it to be used, but I would like to address your case as well. 

For this, we need two readers. I would like to change your usage to the default "DualReader" and give the current reader a different name, what do you think?

**Comment by koriym** [comment]
Hmm, probably not a good idea.
Let's just make your changes, shall we?

**Comment by TomasVotruba** [comment]
> When supporting PHP8, I assumed that both annotations and attributes would be added as follows.



In this case I would expected 2 `Foo` classes. As in these cases:

```php
/**
 * @Foo
 */
#[Foo]
class Fake
{
}
```

```php
/**
 * @Foo
 * @Foo
 */
class Fake
{
}
```

```php
#[Foo]
#[Foo]
class Fake
{
}
```

They are all equal, just with different syntax.

**Comment by TomasVotruba** [comment]
> Hmm, probably not a good idea.
> Let's just make your changes, shall we?

I'm on it :+1:  :)

**Comment by koriym** [comment]
> I can fix it here... shall I send PR?

Please do it!
