### ISSUE TITLE
Doctrine annotation 2.0.x

### ISSUE THREAD

**Issue by Guillaume-friesenhahn** [koriym/Koriym.Attributes#22]
Hi,

Currently on this package, doctrine annotation dependency is on version 1.x, is there any plan to upgrade to 2.x? (Php 8.2 support)

https://github.com/koriym/Koriym.Attributes/blob/a7ccfea76dd319be5bd065e847f79cb39ff949a9/composer.json#L14

Thanks

**Comment by koriym** [comment]
Released as https://github.com/koriym/Koriym.Attributes/releases/tag/1.0.5

**Comment by koriym** [comment]
@Guillaume-friesenhahn Thanks for letting us know about the problem.

**Comment by Guillaume-friesenhahn** [comment]
Thank you for your work
